CI: fix: can't comment on locked issues (#2203)

diff --git a/.github/workflows/gh-release-issue-commenter.yml b/.github/workflows/gh-release-issue-commenter.yml
--- a/.github/workflows/gh-release-issue-commenter.yml
+++ b/.github/workflows/gh-release-issue-commenter.yml
@@ -33,7 +33,6 @@ jobs:
 
       - shell: bash
         run: |
-          REPO="${GITHUB_REPOSITORY}"
           CURR_TAG="${{ env.tag }}"
           CURR_PUBLISHED="$(gh release view "${CURR_TAG}" --json publishedAt --jq '.publishedAt')"
           RELEASE_HTML_URL="$(gh release view "${CURR_TAG}" --json url --jq '.url')"
@@ -71,7 +70,7 @@ jobs:
           for sha in "${COMMITS[@]}"; do
             PRS_FOR_COMMIT=$(gh api \
               -H "Accept: application/vnd.github+json" \
-              "/repos/${REPO}/commits/${sha}/pulls" \
+              "/repos/${GITHUB_REPOSITORY}/commits/${sha}/pulls" \
               --jq '.[].number' 2>/dev/null || true)
             if [ -n "${PRS_FOR_COMMIT}" ]; then
               while IFS= read -r pr; do
@@ -113,16 +112,18 @@ jobs:
           # Comment on each issue
           COMMENT_BODY="$(
             echo "## :rocket: GitHub Release"
-            echo "This fix to this issue was released in [${CURR_TAG}](${RELEASE_HTML_URL})!"
+            echo "The fix to this issue was released in [${CURR_TAG}](${RELEASE_HTML_URL})!"
             echo ""
             echo "_Comment generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}) workflow._"
           )"
           for issue in "${ISSUES_SORTED[@]}"; do
             echo "Processing issue #${issue}..."
-            ALREADY_COMMENTED=$(gh issue view "${issue}" --json comments --jq \
-              '[.comments[].body | contains("comment generated by")] | any' 2>/dev/null || echo "false")
-            if [ "${ALREADY_COMMENTED}" = "true" ]; then
-              echo " - Comment for ${CURR_TAG} already exists on #${issue}; skipping."
+            if [[ "$(gh issue view "${issue}" --json comments --jq '[.comments[].body | contains("${{ github.workflow }}")] | any' 2>/dev/null || echo "false")" == "true" ]]; then
+              echo " - Comment for ${CURR_TAG} already exists on #${issue}, skipping"
+              continue
+            fi
+            if [[ "$(gh api "repos/${GITHUB_REPOSITORY}/issues/${issue}" --jq '.locked' 2>/dev/null || echo "false")" == "true" ]]; then
+              echo " - Issue #${issue} is locked so we can't comment, skipping"
               continue
             fi
             gh issue comment "${issue}" --body "${COMMENT_BODY}"
